name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test the backend
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: Library-System
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: cd LibrarySystem-Backend && mvn clean compile verify package --file pom.xml

    - name: Check test results
      id: tests
      run: |
        if [[ ${{ job.status }} != 'success' ]]; then
          echo "Tests failed"
          echo "tests_failed=true" >> $GITHUB_ENV
        else
          echo "Tests passed"
          echo "tests_failed=false" >> $GITHUB_ENV

    - name: Rollback on test failure
      run: |
        if [ "$tests_failed" == "true" ]; then
          # Revert the last commit
          git revert HEAD --no-edit
          git push origin main
        fi
